export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILED  ="GET_CATEGORIES_FAILED";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const DELETE_CATEGORIY = "DELETE_CATEGORY";
export const ADDING_CATEGORY_ERROR = "ADDING_CATEGORY_ERROR";

export const GET_ITEMS = 'GET_ITEMS';
export const ADDING_ITEM_SUCCESS = 'ADDING_ITEM_SUCCESS';
export const DELETE_ITEM = 'DELETE_ITEM';
export const ITEMS_LOADING = 'ITEMS_LOADING';
export const ADDING_ITEM_ERROR = "ADDING_ITEM_ERROR";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_STATS_UNAVAILABLE = "USER_STATS_UNAVAILABLE";
export const USER_STATS_LOADED = "USER_STATS_LOADED";
export const PRODUCT_STATS_UNAVAILABLE = "PRODUCT_STATS_UNAVAILABLE";
export const PRODUCT_STATS_LOADED = "PRODUCT_STATS_LOADED";



export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';